### ISSUE TITLE
[bug]카테고리명이 없어도 카테고리 생성됨

### ISSUE THREAD

**Issue by aiaaua** [project-565/plog-front#70]
# 발생 경위

카테고리 생성 시 내용을 넣지 않고 추가해도 카테고리가 추가됨

# 발생 내용

![빈카테고리명](https://github.com/project-565/plog-front/assets/55227276/33efda33-f3bb-4224-a292-c9e9586e2411)

# 기대 결과

카테고리명 규칙을 정하고(1글자 이상 등) 해당 규칙 안내

**Comment by YangTaeyoung** [comment]
#68에서 해당 오류를 수정하였음으로 해당 이슈를 종료합니다.
