### ISSUE TITLE
[bug]이미 있는 카테고리명으로 새 카테고리를 생성하려고 할 때 불가능하다는 안내 메세지 없음

### ISSUE THREAD

**Issue by aiaaua** [project-565/plog-front#71]
# 발생 경위

이미 있는 카테고리명으로 새 카테고리를 생성하려고 할 때 불가능하다는 안내메세지가 없어 더블클릭 유도

# 발생 내용

![동일카테고리생성](https://github.com/project-565/plog-front/assets/55227276/8a89829c-94dc-403c-ab57-b088d33ee69c)

# 기대 결과

안내메세지 노출 혹은 textfiled를 통해 유효성검사

**Comment by YangTaeyoung** [comment]
#68 에서 해결했으므로 Close합니다.
