### ISSUE TITLE
[bug]포스팅 종류(공개, 비공개, 임시저장)를 개인 프로그에서 확인이 어려움

### ISSUE THREAD

**Issue by aiaaua** [project-565/plog-front#91]
# 발생 경위

개인 프로그 홈 접속

# 발생 내용

![임시저장비공개확인어려움](https://github.com/project-565/plog-front/assets/55227276/c59f1cae-f3d3-4bef-95ec-f704867a840b)

# 기대 결과

비공개 포스팅, 임시저장 포스팅에 대한 표시 추가

**Comment by YangTaeyoung** [comment]
#110과 dupliicated
