### ISSUE TITLE
[bug] 포스팅 작성시 임시저장 -> 게시하기 버튼 클릭 시 포스팅 게시/저장 됨

### ISSUE THREAD

**Issue by SHINSOJIN** [project-565/plog-front#93]
# 발생 경위

임시저장 설정 -> 게시하기 후 포스팅을 찾을 수 없습니다. 
임시저장한 글이 내 블로그 홈에 나타납니다. 

# 발생 내용

https://github.com/project-565/plog-front/assets/76871305/f67f303c-f497-4710-a0e1-a4a8bcdd74c7

<img width="690" alt="스크린샷 2023-10-25 오후 9 51 35" src="https://github.com/project-565/plog-front/assets/76871305/cdc88aa3-2aae-4ef2-b7c5-97d8375aeb61">

# 기대 결과

임시저장인 경우 포스팅 발행되어 내 블로그 홈에 나타나면 안됨.
추가로 임시저장한 글들을 모아놓을 페이지가 필요할 것 같습니다.

**Comment by YangTaeyoung** [comment]
임시저장을 삭제하는 것으로 결정 -> DB 삭제 완료
